default_agent: travel_companion_basic
agents:
  travel_companion_basic:
    name: travel_companion_basic
    entrypoint: C:/Code/Work/agentcore-demo/capstone_project/backend/runtime/simple_agent/travel_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::711015674645:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-346339bc6e
      execution_role_auto_create: false
      account: '711015674645'
      region: us-east-1
      ecr_repository: 711015674645.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-travel_companion_basic
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
