default_agent: travel_agent_google_drive
agents:
  travel_agent_google_drive:
    name: travel_agent_google_drive
    entrypoint: /Users/puriaizady/Code/mastering-amazon-bedrock-agentcore/capstone_project/backend/identity/runtime/travel_agent_google_drive.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::809690530445:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-e1780fdfdb
      execution_role_auto_create: false
      account: '809690530445'
      region: us-east-1
      ecr_repository: 809690530445.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-travel_agent_google_drive
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: travel_agent_google_drive-ld2GySHdlf
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:809690530445:runtime/travel_agent_google_drive-ld2GySHdlf
      agent_session_id: 749cf8b5-19f3-441b-a0e2-520fee2d3dcf
    codebuild:
      project_name: bedrock-agentcore-travel_agent_google_drive-builder
      execution_role: arn:aws:iam::809690530445:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-e1780fdfdb
      source_bucket: bedrock-agentcore-codebuild-sources-809690530445-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_LATBFMVty/.well-known/openid-configuration
        allowedClients:
        - 49pkake7cbbjoutv01c6p8td7d
    request_header_configuration: null
    oauth_configuration: null
